/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.demo.jsonc --include-runtime=false --env-interface=CloudSaveEnv cloud-save-configuration.d.ts` (hash: 01e8be522a76578f861a5cad8188e6d0)
interface __BaseEnv_CloudSaveEnv {
	CLOUD_SAVES: R2Bucket;
	CLOUD_DB: D1Database;
	CLOUD_AUTH_LIMIT: RateLimit;
	CLOUD_WRITE_LIMIT: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./packages/server/src/worker-demo");
	}
	interface Env extends __BaseEnv_CloudSaveEnv {}
}
interface CloudSaveEnv extends __BaseEnv_CloudSaveEnv {}
